export type Video = { id: string; title: string; channel: string; thumbnail: string; duration: number; durationFormatted: string; webpageUrl: string; isShort: boolean };
export type Segment = { start: number; end: number; startFormatted: string; endFormatted: string; text: string };
export type Transcript = { language: string; isAutoGenerated: boolean; segments: Segment[] };
export type OutputMetadata = { width: number | null; height: number | null; fps: number | null; codec: string | null; sizeBytes: number };
export type Job = { id: string; state: 'Preparing' | 'Downloading' | 'Merging' | 'Ready' | 'Failed'; progress: number | null; error: string | null; output?: OutputMetadata | null };
export const API = (process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000').replace(/\/$/, '');
export class ApiError extends Error { constructor(message: string, public status: number) { super(message); } }
export async function api<T>(path: string, body?: unknown, signal?: AbortSignal): Promise<T> {
  const response = await fetch(`${API}/api/video${path}`, { method: body ? 'POST' : 'GET', headers: body ? { 'Content-Type': 'application/json' } : {}, body: body ? JSON.stringify(body) : undefined, signal });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new ApiError(typeof data.detail === 'string' ? data.detail : 'The server could not complete this request.', response.status);
  return data;
}
export function timestamp(value: number): string {
  const s = Math.max(0, Math.floor(value));
  return [Math.floor(s / 3600), Math.floor(s / 60) % 60, s % 60].map(v => String(v).padStart(2, '0')).join(':');
}
export function parseTime(value: string): number {
  if (!/^\d{2,}:\d{2}:\d{2}(\.\d{1,3})?$/.test(value)) return NaN;
  const [h, m, s] = value.split(':').map(Number);
  return m < 60 && s < 60 ? h * 3600 + m * 60 + s : NaN;
}
export function editTime(value: number): string {
  const ms = Math.round((value - Math.floor(value)) * 1000);
  return timestamp(value) + (ms ? `.${String(ms).padStart(3, '0')}` : '');
}
export function exportTranscript(transcript: Transcript, type: 'txt' | 'srt') {
  const srtTime = (v: number) => { const ms = Math.round(v * 1000); return `${timestamp(Math.floor(ms / 1000))},${String(ms % 1000).padStart(3, '0')}`; };
  const text = transcript.segments.map((s, i) => type === 'txt' ? `${s.startFormatted}  ${s.text}` : `${i + 1}\n${srtTime(s.start)} --> ${srtTime(s.end)}\n${s.text}\n`).join('\n');
  const url = URL.createObjectURL(new Blob([text], { type: 'text/plain;charset=utf-8' }));
  const a = document.createElement('a'); a.href = url; a.download = `transcript.${type}`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}

