import assert from 'node:assert/strict';
import { test } from 'node:test';
import { clipFilename, clipSrt } from './clip-subtitles';
import { Transcript } from './api';

const transcript: Transcript = { language: 'en', isAutoGenerated: false, segments: [
  { start: 10, end: 11, text: 'First', startFormatted: '', endFormatted: '' },
  { start: 11, end: 13, text: 'Removed', startFormatted: '', endFormatted: '' },
  { start: 13, end: 14, text: 'Last', startFormatted: '', endFormatted: '' },
] };
test('silence captions remove discarded cues and shift surviving cues', () => {
  const srt = clipSrt(transcript, 10, 14, [{ start: 0, end: 1 }, { start: 3, end: 4 }]);
  assert.equal(srt, '1\n00:00:00,000 --> 00:00:01,000\nFirst\n\n2\n00:00:01,000 --> 00:00:02,000\nLast\n');
  assert.match(clipSrt(transcript, 10, 14), /00:00:03,000 --> 00:00:04,000/);
});
test('captions crossing cut points are clipped into the same output timeline', () => {
  const source = { ...transcript, segments: [{ ...transcript.segments[0], end: 14 }] };
  assert.equal(clipSrt(source, 10, 14, [{ start: .5, end: 1 }, { start: 3, end: 4 }]),
    '1\n00:00:00,000 --> 00:00:00,500\nFirst\n\n2\n00:00:00,500 --> 00:00:01,500\nFirst\n');
});
test('filename extensions and reserved names are safe for MP4 and SRT', () => {
  assert.equal(clipFilename(' Hook.mp4 '), 'Hook');
  assert.equal(clipFilename('CON'), '_CON');
  assert.equal(clipFilename('../clip'), '_clip');
});
