import time
from pathlib import Path
import pytest
from app.models.video import DownloadRequest, ClipRequest
from app.services.jobs import JobManager
from app.services import jobs, transcript_service
from app.services.video_service import ServiceError

URL = 'https://youtu.be/dQw4w9WgXcQ'
def finish(manager, job_id):
    for _ in range(200):
        result = manager.public(job_id)
        if result['state'] in {'Ready', 'Failed'}: return result
        time.sleep(.01)
    pytest.fail('Job did not finish')

@pytest.fixture
def manager(tmp_path, monkeypatch):
    monkeypatch.setattr('app.services.storage.JOB_ROOT', tmp_path)
    monkeypatch.setattr(jobs, 'JOB_ROOT', tmp_path)
    instance = JobManager()
    yield instance
    instance.pool.shutdown(wait=True)

def test_delivery_cleanup(manager, monkeypatch):
    monkeypatch.setattr(jobs, 'extract', lambda _: {'duration':20})
    def process(url, quality, directory, update):
        path = directory / 'clipper.mp4'; path.write_bytes(b'video'); return path
    monkeypatch.setattr(jobs, 'process', process)
    job = manager.submit(DownloadRequest(url=URL))
    assert finish(manager, job['id'])['state'] == 'Ready'
    path = manager.acquire(job['id'])
    manager.cleanup()
    assert path.exists()
    manager.release(job['id'])
    assert not path.exists()
    assert manager.public(job['id']) is None

def test_busy_rejected(manager, monkeypatch):
    monkeypatch.setattr(manager.pool, 'submit', lambda *args: None)
    manager.submit(DownloadRequest(url=URL))
    with pytest.raises(ServiceError, match='Another video'): manager.submit(DownloadRequest(url=URL))

def test_long_download_fails_before_processing(manager, monkeypatch):
    monkeypatch.setattr(jobs, 'extract', lambda _: {'duration':3601})
    monkeypatch.setattr(jobs, 'process', lambda *args: pytest.fail('Must not download'))
    job = manager.submit(DownloadRequest(url=URL))
    assert '60 minutes' in finish(manager, job['id'])['error']

def test_invalid_clip_fails_before_processing(manager, monkeypatch):
    monkeypatch.setattr(jobs, 'extract', lambda _: {'duration':1000})
    job = manager.submit(ClipRequest(url=URL, start=0, end=301), clip=True)
    assert '5 minutes' in finish(manager, job['id'])['error']

def test_expiration(manager, monkeypatch):
    directory = manager.storage.directory('orphan')
    monkeypatch.setattr(jobs, 'JOB_TTL', -1)
    manager.cleanup()
    assert not directory.exists()

def test_missing_captions(monkeypatch):
    monkeypatch.setattr(transcript_service, 'extract', lambda _: {'duration':100})
    with pytest.raises(ServiceError, match='No captions'): transcript_service.provider.get(URL)

def test_manual_captions_preferred(monkeypatch):
    import io, json
    monkeypatch.setattr(transcript_service, 'extract', lambda _: {
        'duration':100, 'subtitles':{'pl':[{'ext':'json3','url':'https://www.youtube.com/api/timedtext'}]},
        'automatic_captions':{'en':[{'ext':'json3','url':'https://www.youtube.com/api/timedtext'}]}})
    class FakeYDL:
        def __init__(self, opts): pass
        def __enter__(self): return self
        def __exit__(self, *args): pass
        def urlopen(self, url): return io.BytesIO(json.dumps({'events':[{'tStartMs':1250,'dDurationMs':2000,'segs':[{'utf8':'Hello'}]}]}).encode())
    monkeypatch.setattr(transcript_service, 'YoutubeDL', FakeYDL)
    result = transcript_service.provider.get(URL)
    assert result['language'] == 'pl' and result['isAutoGenerated'] is False
    assert result['segments'][0]['start'] == 1.25
    assert result['segments'][0]['end'] == 3.25

def test_section_fallback_stays_bounded(tmp_path, monkeypatch):
    from app.services import download_service as service
    monkeypatch.setattr(service.shutil, 'which', lambda _: 'tool')
    attempts = []
    class FakeYDL:
        def __init__(self, opts): self.opts = opts
        def __enter__(self): return self
        def __exit__(self, *args): pass
        def download(self, urls):
            attempts.append(dict(self.opts))
            (tmp_path / 'source.mp4').write_bytes(b'source')
    monkeypatch.setattr(service, 'YoutubeDL', FakeYDL)
    monkeypatch.setattr(service, 'editor_mp4', lambda source, output, update: output.write_bytes(b'mp4'))
    monkeypatch.setattr(service, 'usable_section', lambda path, duration: len(attempts) == 2)
    result = service.process(URL, '1080', tmp_path, lambda *args: None, section=(5, 10))
    assert result.exists() and len(attempts) == 2
    assert attempts[0]['force_keyframes_at_cuts'] is False
    assert attempts[1]['force_keyframes_at_cuts'] is True
    assert attempts[0]['download_ranges'] is attempts[1]['download_ranges']
    assert list(attempts[1]['download_ranges']({}, None)) == [{'start_time':5, 'end_time':10}]

def test_good_section_avoids_reencoding(tmp_path, monkeypatch):
    from app.services import download_service as service
    monkeypatch.setattr(service.shutil, 'which', lambda _: 'tool')
    attempts = []
    class FakeYDL:
        def __init__(self, opts): attempts.append(dict(opts))
        def __enter__(self): return self
        def __exit__(self, *args): pass
        def download(self, urls): (tmp_path / 'source.mp4').write_bytes(b'source')
    monkeypatch.setattr(service, 'YoutubeDL', FakeYDL)
    monkeypatch.setattr(service, 'editor_mp4', lambda source, output, update: output.write_bytes(b'mp4'))
    monkeypatch.setattr(service, 'usable_section', lambda *args: True)
    service.process(URL, '720', tmp_path, lambda *args: None, section=(0, 5))
    assert len(attempts) == 1 and attempts[0]['force_keyframes_at_cuts'] is False
