import json
from urllib.parse import urlsplit
from yt_dlp import YoutubeDL
from app.services.video_service import extract, options, ServiceError
from app.utils.time import format_time

class CaptionProvider:
    """Replace or compose this provider with speech-to-text in a later version."""
    def get(self, url: str) -> dict:
        info = extract(url)
        selected = None
        for automatic, tracks in [(False, info.get('subtitles', {})), (True, info.get('automatic_captions', {}))]:
            languages = sorted(tracks, key=lambda lang: (not lang.startswith('en'), lang))
            for language in languages:
                track = next((t for t in tracks[language] if t.get('ext') == 'json3'), None)
                if track:
                    selected = (automatic, language, track)
                    break
            if selected:
                break
        if not selected:
            raise ServiceError('No captions are available for this video.')
        automatic, language, track = selected
        host = urlsplit(track['url']).hostname or ''
        if not (host == 'youtube.com' or host.endswith('.youtube.com')):
            raise ServiceError('The caption source is unsupported.')
        try:
            with YoutubeDL(options()) as ydl:
                with ydl.urlopen(track['url']) as response:
                    raw = response.read(10_000_001)
            if len(raw) > 10_000_000:
                raise ServiceError('This caption file is too large.')
            data = json.loads(raw)
        except ServiceError:
            raise
        except Exception:
            raise ServiceError('Captions could not be loaded. Please try again later.') from None
        segments = []
        for event in data.get('events', []):
            text = ''.join(s.get('utf8', '') for s in event.get('segs', [])).strip()
            start = max(0, event.get('tStartMs', 0) / 1000)
            end = min(info['duration'], start + event.get('dDurationMs', 0) / 1000)
            if text and end > start:
                segments.append({'start': start, 'end': end, 'startFormatted': format_time(start),
                                 'endFormatted': format_time(end), 'text': text})
        if not segments:
            raise ServiceError('No usable captions are available for this video.')
        return {'language': language, 'isAutoGenerated': automatic, 'segments': segments}

provider = CaptionProvider()
